### ISSUE TITLE
Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by zjrwtx** [sonofmagic/taro-react-tailwind-vscode-template#3]
![image](https://github.com/user-attachments/assets/f26aede4-5371-4110-b5f2-c78d949a313b)

**Comment by sonofmagic** [comment]
是的，这是由于新版本的 dart sass 的变更导致的，需要给 sass-loader 它传入参数进行忽略警告信息

**Comment by sonofmagic** [comment]
已经在模版里修复

**Comment by Windyskr** [comment]
最新版依然报错，切换回9月老版本可用。
